# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TakeCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TakeCare

	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage' 

  target 'TakeCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TakeCareUITests' do
    # Pods for testing
  end

end
